require("v8tenko.plugins-setup")
require("v8tenko.core.options")
require("v8tenko.core.keymaps")
require("v8tenko.core.colorscheme")
require("v8tenko.plugins.comment")
require("v8tenko.plugins.nvim-tree")
require("v8tenko.plugins.lualine")
require("v8tenko.plugins.telescope")
require("v8tenko.plugins.nvim-cmp")
require("v8tenko.plugins.lsp.mason")
require("v8tenko.plugins.lsp.lspsaga")
require("v8tenko.plugins.lsp.lspconfig")
require("v8tenko.plugins.autopairs")
require("v8tenko.plugins.treesitter")
require("v8tenko.plugins.gitsigns")
require("v8tenko.plugins.buffers")

